---
# tasks file for common
#- import_tasks: packages-Debian.yml
#  when: ansible_os_family == 'Debian'

#- import_tasks: env-Debian.yml
#  when: ansible_os_family == 'Debian'

  - name: test job 
    debug: 
      msg: 
        - "this is a test"
